spring:
  datasource:
    url: jdbc:mysql://localhost:3306/axon
    username: axon
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
axon:
  serializer:
    general: jackson
  axonserver:
    enabled: false