### init
POST http://localhost:8080/init

### create cart
POST http://localhost:8080/cart/create
Content-Type: application/json

{
  "user": "astabile"
}

### add product to cart
POST http://localhost:8080/cart/CA_01HBG0GFZDJZ821NMA4HR208X0/product/PR_01HBG0DWCYSQ6KHT7J576GSHAZ

### remove product to cart
DELETE http://localhost:8080/cart/CA_01HBG0GFZDJZ821NMA4HR208X0/product/PR_01HBG0DWCF279HG44BZMVGEZMC

### checkout cart
POST http://localhost:8080/cart/CA_01HBG0GFZDJZ821NMA4HR208X0/buy

