### create cart
POST http://localhost:8080/cart/create
Content-Type: application/json

{
  "user": "astabile"
}

### add product to cart
POST http://localhost:8080/cart/CA_01H9T4S859VS8CRGDN3AWHWEVN/product
Content-Type: application/json

{
  "name": "Keyboard",
  "amount": {
    "amount": "100",
    "currency": "EUR"
  }
}

### remove product to cart
DELETE http://localhost:8080/cart/CA_01H9T1Y5MJYK0TM5BQPYEDV6EG/product/PR_01H9T2E7CH3HJTTH1S84Q7ZM27

### buy cart
POST http://localhost:8080/cart/CA_01H9T4S859VS8CRGDN3AWHWEVN/buy

