### create cart
POST http://localhost:8080/cart/create
Content-Type: application/json

{
  "user": "astabile"
}

### add product to cart
POST http://localhost:8080/cart/CA_01H9T1Y5MJYK0TM5BQPYEDV6EG/product
Content-Type: application/json

{
  "name": "Keyboard",
  "amount": {
    "amount": "100",
    "currency": "EUR"
  }
}

### remove product to cart
DELETE http://localhost:8080/cart/CA_01H9T1Y5MJYK0TM5BQPYEDV6EG/product/PR_01H9T1YC508BERZ3R6M60RHJ15

### buy cart
POST http://localhost:8080/cart/CA_01H9T1Y5MJYK0TM5BQPYEDV6EG/buy

